### ISSUE TITLE
Optional double factor authentication

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaodjin-signup#16]
Rework the workflow after login to support double factor authentication.

1. Introduce `Contact.verification_token` and `Contact.verification_token_expires_at` fields to hold the second (generated) factor.
2. Based on the design for [get_broker](https://github.com/djaodjin/djaodjin-saas/blob/master/saas/models.py#L3927), retrieve a settings to enable double-factor authentication.
3. Emit a `signal` that will implement sending the verification_token to the user (defaults to e-mail in testsuite).

**Comment by knivets** [comment]
2) what do you mean?

**Comment by smirolo** [comment]
Forget about point number 2. The choice for MFA should be per user, i.e. part of the Contact model.
