### ISSUE TITLE
support multi-tenants

### ISSUE THREAD

**Issue by smirolo** [djaodjin/djaodjin-signup#22]
In signup/settings.py, `DISABLED_AUTHENTICATION`, `DISABLED_REGISTRATION` are used to enable/disable authentication and registration globally. This needs to be changed to use the output of a function instead. The function will look like the following in saas/models.py:

    def get_broker():
        """
        Returns the site-wide provider from a request.
        """
        from saas.compat import import_string
        LOGGER.debug("get_broker('%s')", settings.BROKER_CALLABLE)
        try:
            return import_string(settings.BROKER_CALLABLE)()
        except ImportError:
            pass
        return Organization.objects.get(slug=settings.BROKER_CALLABLE)

**Comment by knivets** [comment]
What exactly needs to be changed? Should the values of DISABLED_AUTHENTICATION and DISABLED_REGISTRATION be populated by calling a function or what? Not sure what to do here.

**Comment by smirolo** [comment]
see commit e59cc614
