### ISSUE TITLE
Builtin registration view is broken

### ISSUE THREAD

**Issue by knivets** [djaodjin/djaodjin-signup#9]
When trying to signup I get this `ValueError: The given username must be set`. The problem is that `username` field is always empty in the file `signup/views/users.py` on the line 266. And apparently the `NameEmailForm` is not expecting a `username` parameter, while the call on line 266 is trying to fetch the field from the form data.

**Comment by smirolo** [comment]
In signup/tests.py we use the following code:

    user_class.objects = ActivatedUserManager()

Same is true in [djaoapp](https://github.com/djaodjin/djaoapp/blob/master/djaoapp/jinja2.py#L38).

The `ActivatedUserManager.create_user` method is specifically designed to take a `username` or `email` and create a `User` out of it.

This seems an issue with the local `testsite`.

**Comment by smirolo** [comment]
fixed in signup/compat.py as part of commit b92bae79
